name: park-land-platform
services:
# Backend API Service
- name: api
  source_dir: /backend
  github:
    repo: getreality/park-land-discovery-platform
    branch: main
  build_command: npm install && npm run build
  run_command: npm start
  environment_slug: node-js
  instance_count: 1
  instance_size_slug: basic-xxs
  http_port: 8080
  routes:
  - path: /api
  envs:
  - key: NODE_ENV
    value: production
  - key: PORT
    value: "8080"
  - key: DATABASE_URL
    value: ${DATABASE_URL}
  - key: JWT_SECRET
    value: ${JWT_SECRET}

# Frontend Static Site Service  
- name: web
  source_dir: /frontend
  github:
    repo: getreality/park-land-discovery-platform
    branch: main
  build_command: npm install && npm run build
  environment_slug: node-js
  instance_count: 1
  instance_size_slug: basic-xxs
  routes:
  - path: /
  envs:
  - key: VITE_API_URL
    value: ${_self.URL}/api
  - key: VITE_MAPBOX_ACCESS_TOKEN
    value: ${MAPBOX_ACCESS_TOKEN}

# Database
databases:
- name: park-land-db
  engine: PG
  version: "15"
  size: db-s-1vcpu-1gb
  num_nodes: 1
